name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/my-site
            git pull origin main
            docker stop my-nginx || true
            docker rm my-nginx || true
            docker run -d -p 80:80 --name my-nginx -v /home/ubuntu/my-site:/usr/share/nginx/html:ro nginx:latest
